name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/zirist
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Debug Node env
        run: |
          node -v
          npm -v
          pwd
          ls -la
      - name: Configure npm (disable audit/fund)
        run: |
          npm config set fund false
          npm config set audit false
      - name: Install deps (with fallback)
        run: |
          set -e
          npm ci --no-audit --no-fund \
            || npm ci --no-audit --no-fund --legacy-peer-deps \
            || npm install --no-audit --no-fund --legacy-peer-deps
      - name: Lint
        run: |
          if npm run 2>/dev/null | grep -qE '^\s*lint\s'; then
            npm run lint || exit 1
          else
            echo "No lint script, skipping"
          fi
      - name: Build
        run: npm run build

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set PYTHONPATH for repo root
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies (if requirements.txt exists)
        run: |
          if [ -f backend/requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r backend/requirements.txt
          else
            echo "No backend/requirements.txt found, skipping install"
          fi
      - name: Run tests (if tests folder exists)
        run: |
          if [ -d backend/tests ]; then
            pip install pytest
            pytest -q backend/tests
          else
            echo "No backend/tests found, skipping tests"
          fi
